version: "3.8"
services:
  flask:
    build: .
    container_name: flask-app
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      - flask`