version: "3.8"
services:
  flask:
    build: .
    container_name: flask-app
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask


